import os
import re
from collections import OrderedDict


VCF_TSV_COL_MAP = OrderedDict(
    [
        ("SAMPLE", "Sample"),
        ("CHROM", "Chrom"),
        ("POS", "Start"),
        ("REF", "Ref"),
        ("ALT", "Alt"),
    ]
)

MAF_TSV_COL_MAP = OrderedDict(
    [
        ("Tumor_Sample_Barcode", "Sample"),
        ("caller_Norm_Sample_Barcode", "NormalUsed"),
        ("Chromosome", "Chrom"),
        # ("Start_Position", "Start"),
        # ("Reference_Allele", "Ref"),
        # ("Tumor_Seq_Allele2", "Alt"),
        ("vcf_pos", "Start"),
        ("VCF_REF", "Ref"),
        ("VCF_ALT", "Alt"),
        ("Variant_Classification", "VariantClass"),
        ("Hugo_Symbol", "Gene"),
        ("Call_Confidence", "Call_Confidence"),
        ("EXON", "Exon"),
        ("Transcript_ID", "TranscriptID"),
        ("Comments", "Comments"),
        ("HGVSc", "cDNAchange"),
        ("HGVSp_Short", "AAchange"),
        ("dbSNP_RS", "dbSNP_ID"),
        ("Cosmic_ID", "Cosmic_ID"),
        ("GMAF", "1000G_MAF"),
        ("FailureReason", "FailureReason"),
        ("CallMethod", "CallMethod"),
        ("COSMIC_site", "COSMIC_site"),
        ("n_count_fragment", "N_TotalDepth"),
        ("n_ref_count_fragment", "N_RefCount"),
        ("n_alt_count_fragment", "N_AltCount"),
        ("n_vaf_fragment", "N_AltFreq"),
        ("T_TotalDepth", "T_TotalDepth"),
        ("T_RefCount", "T_RefCount"),
        ("T_AltCount", "T_AltCount"),
        ("T_AltFreq", "T_AltFreq"),
        ("T_Ref_Pos", "T_Ref+"),
        ("T_Ref_Neg", "T_Ref-"),
        ("T_Alt_Pos", "T_Alt+"),
        ("T_Alt_Neg", "T_Alt-"),
        ("Strand_Bias", "Strand_Bias"),
        ("NORMAL_n_fillout_sample_alt_detect", "All_N_Aggregate_AlleleDepth"),
        ("NORMAL_median_VAF", "All_N_Median_AlleleFreq"),
        ("SD_t_vaf_fragment_over_n_vaf_fragment", "T_freq/All_N_Freq"),
        ("NORMAL_n_fillout_sample", "Occurence_in_Normals"),
        ("gnomAD_Max_AF", "gnomAD_Max_AF"),
        ("gnomAD_AF", "gnomAD_ALL"),
        ("gnomAD_AF_AFR", "gnomAD_AFR"),
        ("gnomAD_AF_AMR", "gnomAD_AMR"),
        ("gnomAD_AF_ASJ", "gnomAD_ASJ"),
        ("gnomAD_AF_EAS", "gnomAD_EAS"),
        ("gnomAD_AF_FIN", "gnomAD_FIN"),
        ("gnomAD_AF_NFE", "gnomAD_NFE"),
        ("gnomAD_AF_OTH", "gnomAD_OTH"),
        ("gnomAD_AF_SAS", "gnomAD_SAS"),
        ("Mutation_Class", "Mutation_Class"),
        ("Status", "Mutation_Status"),
        ("D_t_count_fragment", "D_T_TotalDepth"),
        ("D_t_ref_count_fragment", "D_T_RefCount"),
        ("D_t_alt_count_fragment", "D_T_AltCount"),
        ("D_t_vaf_fragment", "D_T_AltFreq"),
        ("S_t_count_fragment", "S_T_TotalDepth"),
        ("S_t_ref_count_fragment", "S_T_RefCount"),
        ("S_t_alt_count_fragment", "S_T_AltCount"),
        ("S_t_vaf_fragment", "S_T_AltFreq"),
        ("SD_t_count_fragment", "SD_T_TotalDepth"),
        ("SD_t_ref_count_fragment", "SD_T_RefCount"),
        ("SD_t_alt_count_fragment", "SD_T_AltCount"),
        ("SD_t_vaf_fragment", "SD_T_AltFreq"),
        (
            "CURATED_DUPLEX_n_fillout_sample_alt_detect",
            "D_All_curatedN_Aggregate_AlleleDepth",
        ),
        ("CURATED_DUPLEX_median_VAF", "D_All_curatedN_Median_AlleleFreq"),
        ("CURATED_DUPLEX_n_fillout_sample", "D_Occurrence_in_Curated_Normals"),
        (
            "CURATED_SIMPLEX_DUPLEX_n_fillout_sample_alt_detect",
            "SD_All_curatedN_Aggregate_AlleleDepth",
        ),
        ("CURATED_SIMPLEX_DUPLEX_median_VAF", "SD_All_curatedN_Median_AlleleFreq"),
        ("CURATED_SIMPLEX_DUPLEX_n_fillout_sample", "SD_Occurrence_in_Curated_Normals"),
    ]
)
